# Generated by Django 5.0.6 on 2026-04-06 11:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iniciado_em', models.DateTimeField(auto_now_add=True)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'Sucesso'), ('error', 'Erro'), ('partial', 'Parcial')], default='success', max_length=10)),
                ('veiculos_sync', models.IntegerField(default=0)),
                ('alertas_sync', models.IntegerField(default=0)),
                ('eventos_sync', models.IntegerField(default=0)),
                ('erro_msg', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Log de Sincronização',
                'verbose_name_plural': 'Logs de Sincronização',
                'ordering': ['-iniciado_em'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.CharField(max_length=20, unique=True, verbose_name='ID API')),
                ('api_client_id', models.CharField(blank=True, max_length=20)),
                ('placa', models.CharField(blank=True, max_length=20, verbose_name='Placa')),
                ('tag', models.CharField(blank=True, max_length=50, verbose_name='Tag')),
                ('descricao', models.CharField(blank=True, max_length=200, verbose_name='Descrição')),
                ('chassi', models.CharField(blank=True, max_length=50)),
                ('ano', models.CharField(blank=True, max_length=10)),
                ('cor', models.CharField(blank=True, max_length=50)),
                ('tipo', models.CharField(blank=True, max_length=10)),
                ('fabricante', models.CharField(blank=True, max_length=10)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('combustivel', models.CharField(blank=True, max_length=10)),
                ('consumo', models.CharField(blank=True, max_length=20)),
                ('velocidade_limite', models.CharField(blank=True, max_length=20)),
                ('odometro', models.CharField(blank=True, max_length=20)),
                ('equipamento', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('velocidade_atual', models.FloatField(blank=True, null=True)),
                ('ignicao', models.BooleanField(blank=True, null=True)),
                ('ultima_posicao', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'ordering': ['placa'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_event_id', models.CharField(blank=True, max_length=50)),
                ('tipo', models.CharField(blank=True, max_length=100, verbose_name='Tipo')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('velocidade', models.FloatField(blank=True, null=True)),
                ('ocorrido_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.vehicle')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-ocorrido_em'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_alert_id', models.CharField(blank=True, max_length=50)),
                ('tipo', models.CharField(blank=True, max_length=100, verbose_name='Tipo')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('severidade', models.CharField(choices=[('info', 'Informação'), ('warning', 'Atenção'), ('danger', 'Crítico')], default='info', max_length=10)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('lido', models.BooleanField(default=False)),
                ('ocorrido_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.vehicle')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-ocorrido_em'],
            },
        ),
    ]
