# Generated by Django 5.0.6 on 2026-04-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='direcao',
            field=models.FloatField(blank=True, null=True, verbose_name='Direção (graus)'),
        ),
    ]
