# Generated by Django 5.0.6 on 2026-04-06 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_vehicle_direcao'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='veiculos/', verbose_name='Foto'),
        ),
    ]
