# Generated by Django 5.0.6 on 2026-04-06 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_vehicle_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('velocidade', models.FloatField(blank=True, null=True)),
                ('ignicao', models.BooleanField(blank=True, null=True)),
                ('direcao', models.FloatField(blank=True, null=True)),
                ('registrado_em', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='core.vehicle')),
            ],
            options={
                'ordering': ['registrado_em'],
                'indexes': [models.Index(fields=['vehicle', 'registrado_em'], name='core_positi_vehicle_629a7c_idx')],
            },
        ),
    ]
